<?php

use Illuminate\Database\Seeder;



/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class CarrerasTableSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
        public function run()
        {
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Actuación y Teatro', 'nombre_carrera_html' => 'Actuaci&oacute;n y Teatro','nombre_carrera_no_tilde' => 'Actuacion y Teatro'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Administración de Empresas e Ing. Asociadas', 'nombre_carrera_html' => 'Administraci&oacute;n de Empresas e Ing. Asociadas','nombre_carrera_no_tilde' => 'Administracion de Empresas e Ing. Asociadas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Administración Gastronómica', 'nombre_carrera_html' => 'Administraci&oacute;n Gastron&oacute;mica','nombre_carrera_no_tilde' => 'Administracion Gastronomica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Administración Pública', 'nombre_carrera_html' => 'Administraci&oacute;n P&uacute;blica','nombre_carrera_no_tilde' => 'Administracion Publica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Administración Turística y Hotelera', 'nombre_carrera_html' => 'Administraci&oacute;n Tur&iacute;stica y Hotelera','nombre_carrera_no_tilde' => 'Administracion Turistica y Hotelera'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Agronomía', 'nombre_carrera_html' => 'Agronom&iacute;a','nombre_carrera_no_tilde' => 'Agronomia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Analista Químico', 'nombre_carrera_html' => 'Analista Qu&iacute;mico','nombre_carrera_no_tilde' => 'Analista Quimico'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Antropología', 'nombre_carrera_html' => 'Antropolog&iacute;a','nombre_carrera_no_tilde' => 'Antropologia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Arquitectura', 'nombre_carrera_html' => 'Arquitectura','nombre_carrera_no_tilde' => 'Arquitectura'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Artes y Licenciatura en Artes', 'nombre_carrera_html' => 'Artes y Licenciatura en Artes','nombre_carrera_no_tilde' => 'Artes y Licenciatura en Artes'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Bibliotecología', 'nombre_carrera_html' => 'Bibliotecolog&iacute;a','nombre_carrera_no_tilde' => 'Bibliotecologia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Biología', 'nombre_carrera_html' => 'Biolog&iacute;a','nombre_carrera_no_tilde' => 'Biologia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Biología Marina y Ecología Marina', 'nombre_carrera_html' => 'Biolog&iacute;a Marina y Ecolog&iacute;a Marina','nombre_carrera_no_tilde' => 'Biologia Marina y Ecologia Marina'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Bioquímica', 'nombre_carrera_html' => 'Bioqu&iacute;mica','nombre_carrera_no_tilde' => 'Bioquimica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ciencias Políticas', 'nombre_carrera_html' => 'Ciencias Pol&iacute;ticas','nombre_carrera_no_tilde' => 'Ciencias Politicas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Comunicación Audiovisual y/o Multimedia', 'nombre_carrera_html' => 'Comunicaci&oacute;n Audiovisual y/o Multimedia','nombre_carrera_no_tilde' => 'Comunicacion Audiovisual y/o Multimedia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Construcción Civil', 'nombre_carrera_html' => 'Construcci&oacute;n Civil','nombre_carrera_no_tilde' => 'Construccion Civil'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Contador Auditor', 'nombre_carrera_html' => 'Contador Auditor','nombre_carrera_no_tilde' => 'Contador Auditor'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Criminalística', 'nombre_carrera_html' => 'Criminal&iacute;stica','nombre_carrera_no_tilde' => 'Criminalistica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Derecho', 'nombre_carrera_html' => 'Derecho','nombre_carrera_no_tilde' => 'Derecho'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Diseño', 'nombre_carrera_html' => 'Dise&ntilde;o','nombre_carrera_no_tilde' => 'Diseño'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Diseño de Ambientes e Interiores', 'nombre_carrera_html' => 'Dise&ntilde;o de Ambientes e Interiores','nombre_carrera_no_tilde' => 'Diseño de Ambientes e Interiores'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Diseño de Vestuario', 'nombre_carrera_html' => 'Dise&ntilde;o de Vestuario','nombre_carrera_no_tilde' => 'Diseño de Vestuario'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Diseño Gráfico', 'nombre_carrera_html' => 'Dise&ntilde;o Gr&aacute;fico','nombre_carrera_no_tilde' => 'Diseño Grafico'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Diseño Industrial', 'nombre_carrera_html' => 'Dise&ntilde;o Industrial','nombre_carrera_no_tilde' => 'Diseño Industrial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Enfermería', 'nombre_carrera_html' => 'Enfermer&iacute;a','nombre_carrera_no_tilde' => 'Enfermeria'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Filosofía', 'nombre_carrera_html' => 'Filosof&iacute;a','nombre_carrera_no_tilde' => 'Filosofia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Física y Astronomía', 'nombre_carrera_html' => 'F&iacute;sica y Astronom&iacute;a','nombre_carrera_no_tilde' => 'Fisica y Astronomia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Fonoaudiología', 'nombre_carrera_html' => 'Fonoaudiolog&iacute;a','nombre_carrera_no_tilde' => 'Fonoaudiologia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Fotografía', 'nombre_carrera_html' => 'Fotograf&iacute;a','nombre_carrera_no_tilde' => 'Fotografia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Geografía', 'nombre_carrera_html' => 'Geograf&iacute;a','nombre_carrera_no_tilde' => 'Geografia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Geología', 'nombre_carrera_html' => 'Geolog&iacute;a','nombre_carrera_no_tilde' => 'Geologia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Historia', 'nombre_carrera_html' => 'Historia','nombre_carrera_no_tilde' => 'Historia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Agrícola', 'nombre_carrera_html' => 'Ingenier&iacute;a Agr&iacute;cola','nombre_carrera_no_tilde' => 'Ingenieria Agricola'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Agroindustrial', 'nombre_carrera_html' => 'Ingenier&iacute;a Agroindustrial','nombre_carrera_no_tilde' => 'Ingenieria Agroindustrial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil Agrícola', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil Agr&iacute;cola','nombre_carrera_no_tilde' => 'Ingenieria Civil Agricola'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil Ambiental', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil Ambiental','nombre_carrera_no_tilde' => 'Ingenieria Civil Ambiental'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil Bioquímica', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil Bioqu&iacute;mica','nombre_carrera_no_tilde' => 'Ingenieria Civil Bioquimica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil Eléctrica', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil El&eacute;ctrica','nombre_carrera_no_tilde' => 'Ingenieria Civil Electrica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil Electrónica', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil Electr&oacute;nica','nombre_carrera_no_tilde' => 'Ingenieria Civil Electronica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil en Biotecnología y/o Bioingeniería', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil en Biotecnolog&iacute;a y/o Bioingenier&iacute;a','nombre_carrera_no_tilde' => 'Ingenieria Civil en Biotecnologia y/o Bioingenieria'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil en Computación e Informática', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil en Computaci&oacute;n e Inform&aacute;tica','nombre_carrera_no_tilde' => 'Ingenieria Civil en Computacion e Informatica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil en Minas', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil en Minas','nombre_carrera_no_tilde' => 'Ingenieria Civil en Minas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil en Obras Civiles', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil en Obras Civiles','nombre_carrera_no_tilde' => 'Ingenieria Civil en Obras Civiles'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil Industrial', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil Industrial','nombre_carrera_no_tilde' => 'Ingenieria Civil Industrial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil Mecánica', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil Mec&aacute;nica','nombre_carrera_no_tilde' => 'Ingenieria Civil Mecanica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil Metalúrgica', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil Metal&uacute;rgica','nombre_carrera_no_tilde' => 'Ingenieria Civil Metalurgica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil Química', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil Qu&iacute;mica','nombre_carrera_no_tilde' => 'Ingenieria Civil Quimica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Civil, plan común y licenciatura en Ciencias de la Ingeniería', 'nombre_carrera_html' => 'Ingenier&iacute;a Civil, plan com&uacute;n y licenciatura en Ciencias de la Ingenier&iacute;a','nombre_carrera_no_tilde' => 'Ingenieria Civil, plan comun y licenciatura en Ciencias de la Ingenieria'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Comercial', 'nombre_carrera_html' => 'Ingenier&iacute;a Comercial','nombre_carrera_no_tilde' => 'Ingenieria Comercial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Acuicultura y Pesca', 'nombre_carrera_html' => 'Ingenier&iacute;a en Acuicultura y Pesca','nombre_carrera_no_tilde' => 'Ingenieria en Acuicultura y Pesca'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Alimentos', 'nombre_carrera_html' => 'Ingenier&iacute;a en Alimentos','nombre_carrera_no_tilde' => 'Ingenieria en Alimentos'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Automatización, Instrumentación y Control', 'nombre_carrera_html' => 'Ingenier&iacute;a en Automatizaci&oacute;n, Instrumentaci&oacute;n y Control','nombre_carrera_no_tilde' => 'Ingenieria en Automatizacion, Instrumentacion y Control'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Biotecnología y Bioingeniería', 'nombre_carrera_html' => 'Ingenier&iacute;a en Biotecnolog&iacute;a y Bioingenier&iacute;a','nombre_carrera_no_tilde' => 'Ingenieria en Biotecnologia y Bioingenieria'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Comercio Exterior', 'nombre_carrera_html' => 'Ingenier&iacute;a en Comercio Exterior','nombre_carrera_no_tilde' => 'Ingenieria en Comercio Exterior'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Computación e Informática', 'nombre_carrera_html' => 'Ingenier&iacute;a en Computaci&oacute;n e Inform&aacute;tica','nombre_carrera_no_tilde' => 'Ingenieria en Computacion e Informatica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Conectividad y Redes', 'nombre_carrera_html' => 'Ingenier&iacute;a en Conectividad y Redes','nombre_carrera_no_tilde' => 'Ingenieria en Conectividad y Redes'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Construcción', 'nombre_carrera_html' => 'Ingenier&iacute;a en Construcci&oacute;n','nombre_carrera_no_tilde' => 'Ingenieria en Construccion'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Control de Gestión', 'nombre_carrera_html' => 'Ingenier&iacute;a en Control de Gesti&oacute;n','nombre_carrera_no_tilde' => 'Ingenieria en Control de Gestion'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Electricidad', 'nombre_carrera_html' => 'Ingenier&iacute;a en Electricidad','nombre_carrera_no_tilde' => 'Ingenieria en Electricidad'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Electrónica', 'nombre_carrera_html' => 'Ingenier&iacute;a en Electr&oacute;nica','nombre_carrera_no_tilde' => 'Ingenieria en Electronica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Finanzas', 'nombre_carrera_html' => 'Ingenier&iacute;a en Finanzas','nombre_carrera_no_tilde' => 'Ingenieria en Finanzas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Geomensura y Cartografía', 'nombre_carrera_html' => 'Ingenier&iacute;a en Geomensura y Cartograf&iacute;a','nombre_carrera_no_tilde' => 'Ingenieria en Geomensura y Cartografia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Gestión Pública', 'nombre_carrera_html' => 'Ingenier&iacute;a en Gesti&oacute;n P&uacute;blica','nombre_carrera_no_tilde' => 'Ingenieria en Gestion Publica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Logística', 'nombre_carrera_html' => 'Ingenier&iacute;a en Log&iacute;stica','nombre_carrera_no_tilde' => 'Ingenieria en Logistica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Marketing', 'nombre_carrera_html' => 'Ingenier&iacute;a en Marketing','nombre_carrera_no_tilde' => 'Ingenieria en Marketing'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Matemática y Estadística', 'nombre_carrera_html' => 'Ingenier&iacute;a en Matem&aacute;tica y Estad&iacute;stica','nombre_carrera_no_tilde' => 'Ingenieria en Matematica y Estadistica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Mecánica Automotriz', 'nombre_carrera_html' => 'Ingenier&iacute;a en Mec&aacute;nica Automotriz','nombre_carrera_no_tilde' => 'Ingenieria en Mecanica Automotriz'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Medio Ambiente', 'nombre_carrera_html' => 'Ingenier&iacute;a en Medio Ambiente','nombre_carrera_no_tilde' => 'Ingenieria en Medio Ambiente'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Minas y Metalurgia', 'nombre_carrera_html' => 'Ingenier&iacute;a en Minas y Metalurgia','nombre_carrera_no_tilde' => 'Ingenieria en Minas y Metalurgia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Prevención de Riesgos', 'nombre_carrera_html' => 'Ingenier&iacute;a en Prevenci&oacute;n de Riesgos','nombre_carrera_no_tilde' => 'Ingenieria en Prevencion de Riesgos'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Química', 'nombre_carrera_html' => 'Ingenier&iacute;a en Qu&iacute;mica','nombre_carrera_no_tilde' => 'Ingenieria en Quimica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Recursos Humanos', 'nombre_carrera_html' => 'Ingenier&iacute;a en Recursos Humanos','nombre_carrera_no_tilde' => 'Ingenieria en Recursos Humanos'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Recursos Renovables', 'nombre_carrera_html' => 'Ingenier&iacute;a en Recursos Renovables','nombre_carrera_no_tilde' => 'Ingenieria en Recursos Renovables'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Refrigeración y Climatización', 'nombre_carrera_html' => 'Ingenier&iacute;a en Refrigeraci&oacute;n y Climatizaci&oacute;n','nombre_carrera_no_tilde' => 'Ingenieria en Refrigeracion y Climatizacion'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Sonido', 'nombre_carrera_html' => 'Ingenier&iacute;a en Sonido','nombre_carrera_no_tilde' => 'Ingenieria en Sonido'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Telecomunicaciones', 'nombre_carrera_html' => 'Ingenier&iacute;a en Telecomunicaciones','nombre_carrera_no_tilde' => 'Ingenieria en Telecomunicaciones'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Telemática', 'nombre_carrera_html' => 'Ingenier&iacute;a en Telem&aacute;tica','nombre_carrera_no_tilde' => 'Ingenieria en Telematica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería en Transporte y Tránsito', 'nombre_carrera_html' => 'Ingenier&iacute;a en Transporte y Tr&aacute;nsito','nombre_carrera_no_tilde' => 'Ingenieria en Transporte y Transito'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Forestal', 'nombre_carrera_html' => 'Ingenier&iacute;a Forestal','nombre_carrera_no_tilde' => 'Ingenieria Forestal'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Industrial', 'nombre_carrera_html' => 'Ingenier&iacute;a Industrial','nombre_carrera_no_tilde' => 'Ingenieria Industrial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Marina y Marítimo Portuaria', 'nombre_carrera_html' => 'Ingenier&iacute;a Marina y Mar&iacute;timo Portuaria','nombre_carrera_no_tilde' => 'Ingenieria Marina y Maritimo Portuaria'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Mecánica', 'nombre_carrera_html' => 'Ingenier&iacute;a Mec&aacute;nica','nombre_carrera_no_tilde' => 'Ingenieria Mecanica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Ingeniería Naval', 'nombre_carrera_html' => 'Ingenier&iacute;a Naval','nombre_carrera_no_tilde' => 'Ingenieria Naval'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Kinesiología', 'nombre_carrera_html' => 'Kinesiolog&iacute;a','nombre_carrera_no_tilde' => 'Kinesiologia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Licenciatura en Gestión', 'nombre_carrera_html' => 'Licenciatura en Gesti&oacute;n','nombre_carrera_no_tilde' => 'Licenciatura en Gestion'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Licenciatura en Letras y Literatura', 'nombre_carrera_html' => 'Licenciatura en Letras y Literatura','nombre_carrera_no_tilde' => 'Licenciatura en Letras y Literatura'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Matemáticas y/o Estadísticas', 'nombre_carrera_html' => 'Matem&aacute;ticas y/o Estad&iacute;sticas','nombre_carrera_no_tilde' => 'Matematicas y/o Estadisticas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Medicina', 'nombre_carrera_html' => 'Medicina','nombre_carrera_no_tilde' => 'Medicina'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Medicina Veterinaria', 'nombre_carrera_html' => 'Medicina Veterinaria','nombre_carrera_no_tilde' => 'Medicina Veterinaria'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Música, Canto o Danza', 'nombre_carrera_html' => 'M&uacute;sica, Canto o Danza','nombre_carrera_no_tilde' => 'Musica, Canto o Danza'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Nutrición y Dietética', 'nombre_carrera_html' => 'Nutrici&oacute;n y Diet&eacute;tica','nombre_carrera_no_tilde' => 'Nutricion y Dietetica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Obstetricia y Puericultura', 'nombre_carrera_html' => 'Obstetricia y Puericultura','nombre_carrera_no_tilde' => 'Obstetricia y Puericultura'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Odontología', 'nombre_carrera_html' => 'Odontolog&iacute;a','nombre_carrera_no_tilde' => 'Odontologia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Orientación Familiar y Relaciones Humanas', 'nombre_carrera_html' => 'Orientaci&oacute;n Familiar y Relaciones Humanas','nombre_carrera_no_tilde' => 'Orientacion Familiar y Relaciones Humanas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Artes y Música', 'nombre_carrera_html' => 'Pedagog&iacute;a en Artes y M&uacute;sica','nombre_carrera_no_tilde' => 'Pedagogia en Artes y Musica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Ciencias', 'nombre_carrera_html' => 'Pedagog&iacute;a en Ciencias','nombre_carrera_no_tilde' => 'Pedagogia en Ciencias'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Educación Básica', 'nombre_carrera_html' => 'Pedagog&iacute;a en Educaci&oacute;n B&aacute;sica','nombre_carrera_no_tilde' => 'Pedagogia en Educacion Basica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Educación de Párvulos', 'nombre_carrera_html' => 'Pedagog&iacute;a en Educaci&oacute;n de P&aacute;rvulos','nombre_carrera_no_tilde' => 'Pedagogia en Educacion de Parvulos'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Educación Diferencial', 'nombre_carrera_html' => 'Pedagog&iacute;a en Educaci&oacute;n Diferencial','nombre_carrera_no_tilde' => 'Pedagogia en Educacion Diferencial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Educación Física', 'nombre_carrera_html' => 'Pedagog&iacute;a en Educaci&oacute;n F&iacute;sica','nombre_carrera_no_tilde' => 'Pedagogia en Educacion Fisica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Educación Media', 'nombre_carrera_html' => 'Pedagog&iacute;a en Educaci&ograve;n Media','nombre_carrera_no_tilde' => 'Pedagogia en Educaci&ograve;n Media'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Educación Técnico Profesional', 'nombre_carrera_html' => 'Pedagog&iacute;a en Educaci&oacute;n T&eacute;cnico Profesional','nombre_carrera_no_tilde' => 'Pedagogia en Educacion Tecnico Profesional'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Filosofía y Religión', 'nombre_carrera_html' => 'Pedagog&iacute;a en Filosof&iacute;a y Religi&oacute;n','nombre_carrera_no_tilde' => 'Pedagogia en Filosofia y Religion'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Historia, Geografía y Ciencias Sociales', 'nombre_carrera_html' => 'Pedagog&iacute;a en Historia, Geograf&iacute;a y Ciencias Sociales','nombre_carrera_no_tilde' => 'Pedagogia en Historia, Geografia y Ciencias Sociales'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Idiomas', 'nombre_carrera_html' => 'Pedagog&iacute;a en Idiomas','nombre_carrera_no_tilde' => 'Pedagogia en Idiomas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Lenguaje, Comunicación y/o Castellano', 'nombre_carrera_html' => 'Pedagog&iacute;a en Lenguaje, Comunicaci&oacute;n y/o Castellano','nombre_carrera_no_tilde' => 'Pedagogia en Lenguaje, Comunicacion y/o Castellano'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Pedagogía en Matemáticas y Computación', 'nombre_carrera_html' => 'Pedagog&iacute;a en Matem&aacute;ticas y Computaci&oacute;n','nombre_carrera_no_tilde' => 'Pedagogia en Matematicas y Computacion'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Periodismo', 'nombre_carrera_html' => 'Periodismo','nombre_carrera_no_tilde' => 'Periodismo'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Programas de Formación Pedagógica', 'nombre_carrera_html' => 'Programas de Formaci&oacute;n Pedag&oacute;gica','nombre_carrera_no_tilde' => 'Programas de Formacion Pedagogica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Psicología', 'nombre_carrera_html' => 'Psicolog&iacute;a','nombre_carrera_no_tilde' => 'Psicologia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Psicopedagogía', 'nombre_carrera_html' => 'Psicopedagog&iacute;a','nombre_carrera_no_tilde' => 'Psicopedagogia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Publicidad', 'nombre_carrera_html' => 'Publicidad','nombre_carrera_no_tilde' => 'Publicidad'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Química Ambiental', 'nombre_carrera_html' => 'Qu&iacute;mica Ambiental','nombre_carrera_no_tilde' => 'Quimica Ambiental'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Química Industrial', 'nombre_carrera_html' => 'Qu&iacute;mica Industrial','nombre_carrera_no_tilde' => 'Quimica Industrial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Química y Farmacia', 'nombre_carrera_html' => 'Qu&iacute;mica y Farmacia','nombre_carrera_no_tilde' => 'Quimica y Farmacia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Química, Licenciado en Química', 'nombre_carrera_html' => 'Qu&iacute;mica, Licenciado en Qu&iacute;mica','nombre_carrera_no_tilde' => 'Quimica, Licenciado en Quimica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Realizador de Cine y Televisión', 'nombre_carrera_html' => 'Realizador de Cine y Televisi&oacute;n','nombre_carrera_no_tilde' => 'Realizador de Cine y Television'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Relaciones Públicas', 'nombre_carrera_html' => 'Relaciones P&uacute;blicas','nombre_carrera_no_tilde' => 'Relaciones Publicas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Secretariado Biling&uuml;e', 'nombre_carrera_html' => 'Secretariado Biling&uuml;e','nombre_carrera_no_tilde' => 'Secretariado Biling&uuml;e'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Secretariado Computacional', 'nombre_carrera_html' => 'Secretariado Computacional','nombre_carrera_no_tilde' => 'Secretariado Computacional'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Secretariado Ejecutivo', 'nombre_carrera_html' => 'Secretariado Ejecutivo','nombre_carrera_no_tilde' => 'Secretariado Ejecutivo'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Sociología', 'nombre_carrera_html' => 'Sociolog&iacute;a','nombre_carrera_no_tilde' => 'Sociologia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico Agente o Visitador Médico', 'nombre_carrera_html' => 'T&eacute;cnico Agente o Visitador M&eacute;dico','nombre_carrera_no_tilde' => 'Tecnico Agente o Visitador Medico'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico Agropecuario', 'nombre_carrera_html' => 'T&eacute;cnico Agropecuario','nombre_carrera_no_tilde' => 'Tecnico Agropecuario'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico Asistente del Educador de Párvulos', 'nombre_carrera_html' => 'T&eacute;cnico Asistente del Educador de P&aacute;rvulos','nombre_carrera_no_tilde' => 'Tecnico Asistente del Educador de Parvulos'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico Asistente del Educador Diferencial', 'nombre_carrera_html' => 'T&eacute;cnico Asistente del Educador Diferencial','nombre_carrera_no_tilde' => 'Tecnico Asistente del Educador Diferencial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico Dental y Asistente de Odontología', 'nombre_carrera_html' => 'T&eacute;cnico Dental y Asistente de Odontolog&iacute;a','nombre_carrera_no_tilde' => 'Tecnico Dental y Asistente de Odontologia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Acuicultura y Pesca', 'nombre_carrera_html' => 'T&eacute;cnico en Acuicultura y Pesca','nombre_carrera_no_tilde' => 'Tecnico en Acuicultura y Pesca'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Administración de Empresas', 'nombre_carrera_html' => 'T&eacute;cnico en Administraci&oacute;n de Empresas','nombre_carrera_no_tilde' => 'Tecnico en Administracion de Empresas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Administración de Recursos Humanos y Personal', 'nombre_carrera_html' => 'T&eacute;cnico en Administraci&oacute;n de Recursos Humanos y Personal','nombre_carrera_no_tilde' => 'Tecnico en Administracion de Recursos Humanos y Personal'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Administración de Redes y Soporte', 'nombre_carrera_html' => 'T&eacute;cnico en Administraci&oacute;n de Redes y Soporte','nombre_carrera_no_tilde' => 'Tecnico en Administracion de Redes y Soporte'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Administración de Ventas', 'nombre_carrera_html' => 'T&eacute;cnico en Administraci&oacute;n de Ventas','nombre_carrera_no_tilde' => 'Tecnico en Administracion de Ventas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Administración Financiera y Finanzas', 'nombre_carrera_html' => 'T&eacute;cnico en Administraci&oacute;n Financiera y Finanzas','nombre_carrera_no_tilde' => 'Tecnico en Administracion Financiera y Finanzas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Administración Pública o Municipal', 'nombre_carrera_html' => 'T&eacute;cnico en Administraci&oacute;n P&uacute;blica o Municipal','nombre_carrera_no_tilde' => 'Tecnico en Administracion Publica o Municipal'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Alimentos', 'nombre_carrera_html' => 'T&eacute;cnico en Alimentos','nombre_carrera_no_tilde' => 'Tecnico en Alimentos'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Ambientes e Interiores', 'nombre_carrera_html' => 'T&eacute;cnico en Ambientes e Interiores','nombre_carrera_no_tilde' => 'Tecnico en Ambientes e Interiores'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Análisis de Sistemas', 'nombre_carrera_html' => 'T&eacute;cnico en An&aacute;lisis de Sistemas','nombre_carrera_no_tilde' => 'Tecnico en Analisis de Sistemas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Arsenaleria Quirúrgica', 'nombre_carrera_html' => 'T&eacute;cnico en Arsenaleria Quir&uacute;rgica','nombre_carrera_no_tilde' => 'Tecnico en Arsenaleria Quirurgica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Bibliotecas y Centros de Documentación', 'nombre_carrera_html' => 'T&eacute;cnico en Bibliotecas y Centros de Documentaci&oacute;n','nombre_carrera_no_tilde' => 'Tecnico en Bibliotecas y Centros de Documentacion'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Biotecnología Industrial', 'nombre_carrera_html' => 'T&eacute;cnico en Biotecnolog&iacute;a Industrial','nombre_carrera_no_tilde' => 'Tecnico en Biotecnologia Industrial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Comercio Exterior', 'nombre_carrera_html' => 'T&eacute;cnico en Comercio Exterior','nombre_carrera_no_tilde' => 'Tecnico en Comercio Exterior'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Computación e Informática', 'nombre_carrera_html' => 'T&eacute;cnico en Computaci&oacute;n e Inform&aacute;tica','nombre_carrera_no_tilde' => 'Tecnico en Computacion e Informatica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Comunicación Audiovisual', 'nombre_carrera_html' => 'T&eacute;cnico en Comunicaci&oacute;n Audiovisual','nombre_carrera_no_tilde' => 'Tecnico en Comunicacion Audiovisual'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Construcción y Obras Civiles', 'nombre_carrera_html' => 'T&eacute;cnico en Construcci&oacute;n y Obras Civiles','nombre_carrera_no_tilde' => 'Tecnico en Construccion y Obras Civiles'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Contabilidad Computacional', 'nombre_carrera_html' => 'T&eacute;cnico en Contabilidad Computacional','nombre_carrera_no_tilde' => 'Tecnico en Contabilidad Computacional'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Contabilidad General', 'nombre_carrera_html' => 'T&eacute;cnico en Contabilidad General','nombre_carrera_no_tilde' => 'Tecnico en Contabilidad General'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Contabilidad Tributaria', 'nombre_carrera_html' => 'T&eacute;cnico en Contabilidad Tributaria','nombre_carrera_no_tilde' => 'Tecnico en Contabilidad Tributaria'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Deporte, Recreación y Preparación Física', 'nombre_carrera_html' => 'T&eacute;cnico en Deporte, Recreaci&oacute;n y Preparaci&oacute;n F&iacute;sica','nombre_carrera_no_tilde' => 'Tecnico en Deporte, Recreacion y Preparacion Fisica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Dibujo Arquitectónico', 'nombre_carrera_html' => 'T&eacute;cnico en Dibujo Arquitect&oacute;nico','nombre_carrera_no_tilde' => 'Tecnico en Dibujo Arquitectonico'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Dibujo Técnico e Industrial', 'nombre_carrera_html' => 'T&eacute;cnico en Dibujo T&eacute;cnico e Industrial','nombre_carrera_no_tilde' => 'Tecnico en Dibujo Tecnico e Industrial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Diseño de áreas Verdes y Paisajismo', 'nombre_carrera_html' => 'T&eacute;cnico en Dise&ntilde;o de &aacute;reas Verdes y Paisajismo','nombre_carrera_no_tilde' => 'Tecnico en Diseño de areas Verdes y Paisajismo'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Diseño de Vestuario', 'nombre_carrera_html' => 'T&eacute;cnico en Dise&ntilde;o de Vestuario','nombre_carrera_no_tilde' => 'Tecnico en Diseño de Vestuario'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Diseño Gráfico', 'nombre_carrera_html' => 'T&eacute;cnico en Dise&ntilde;o Gr&aacute;fico','nombre_carrera_no_tilde' => 'Tecnico en Diseño Grafico'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Electricidad y Electricidad Industrial', 'nombre_carrera_html' => 'T&eacute;cnico en Electricidad y Electricidad Industrial','nombre_carrera_no_tilde' => 'Tecnico en Electricidad y Electricidad Industrial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Electromecánica', 'nombre_carrera_html' => 'T&eacute;cnico en Electromec&aacute;nica','nombre_carrera_no_tilde' => 'Tecnico en Electromecanica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Electrónica y Electrónica Industrial', 'nombre_carrera_html' => 'T&eacute;cnico en Electr&oacute;nica y Electr&oacute;nica Industrial','nombre_carrera_no_tilde' => 'Tecnico en Electronica y Electronica Industrial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Enfermería', 'nombre_carrera_html' => 'T&eacute;cnico en Enfermer&iacute;a','nombre_carrera_no_tilde' => 'Tecnico en Enfermeria'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Farmacia', 'nombre_carrera_html' => 'T&eacute;cnico en Farmacia','nombre_carrera_no_tilde' => 'Tecnico en Farmacia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Fotografía', 'nombre_carrera_html' => 'T&eacute;cnico en Fotograf&iacute;a','nombre_carrera_no_tilde' => 'Tecnico en Fotografia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Gastronomía y Cocina', 'nombre_carrera_html' => 'T&eacute;cnico en Gastronom&iacute;a y Cocina','nombre_carrera_no_tilde' => 'Tecnico en Gastronomia y Cocina'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Geominería', 'nombre_carrera_html' => 'T&eacute;cnico en Geominer&iacute;a','nombre_carrera_no_tilde' => 'Tecnico en Geomineria'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Gestión Previsional', 'nombre_carrera_html' => 'T&eacute;cnico en Gesti&oacute;n Previsional','nombre_carrera_no_tilde' => 'Tecnico en Gestion Previsional'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Gestión y Control de Calidad', 'nombre_carrera_html' => 'T&eacute;cnico en Gesti&oacute;n y Control de Calidad','nombre_carrera_no_tilde' => 'Tecnico en Gestion y Control de Calidad'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Instrumentación, Automatización y Control Industrial', 'nombre_carrera_html' => 'T&eacute;cnico en Instrumentaci&oacute;n, Automatizaci&oacute;n y Control Industrial','nombre_carrera_no_tilde' => 'Tecnico en Instrumentacion, Automatizacion y Control Industrial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Laboratorio Clínico', 'nombre_carrera_html' => 'T&eacute;cnico en Laboratorio Cl&iacute;nico','nombre_carrera_no_tilde' => 'Tecnico en Laboratorio Clinico'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Logística', 'nombre_carrera_html' => 'T&eacute;cnico en Log&iacute;stica','nombre_carrera_no_tilde' => 'Tecnico en Logistica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Mantenimiento Industrial', 'nombre_carrera_html' => 'T&eacute;cnico en Mantenimiento Industrial','nombre_carrera_no_tilde' => 'Tecnico en Mantenimiento Industrial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Masoterapia', 'nombre_carrera_html' => 'T&eacute;cnico en Masoterapia','nombre_carrera_no_tilde' => 'Tecnico en Masoterapia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Matriceria', 'nombre_carrera_html' => 'T&eacute;cnico en Matriceria','nombre_carrera_no_tilde' => 'Tecnico en Matriceria'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Mecánica Automotriz', 'nombre_carrera_html' => 'T&eacute;cnico en Mec&aacute;nica Automotriz','nombre_carrera_no_tilde' => 'Tecnico en Mecanica Automotriz'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Mecánica Industrial', 'nombre_carrera_html' => 'T&eacute;cnico en Mec&aacute;nica Industrial','nombre_carrera_no_tilde' => 'Tecnico en Mecanica Industrial'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Minería y Metalurgia', 'nombre_carrera_html' => 'T&eacute;cnico en Miner&iacute;a y Metalurgia','nombre_carrera_no_tilde' => 'Tecnico en Mineria y Metalurgia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Nutrición y Dietética', 'nombre_carrera_html' => 'T&eacute;cnico en Nutrici&oacute;n y Diet&eacute;tica','nombre_carrera_no_tilde' => 'Tecnico en Nutricion y Dietetica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Peluquería y Estética', 'nombre_carrera_html' => 'T&eacute;cnico en Peluquer&iacute;a y Est&eacute;tica','nombre_carrera_no_tilde' => 'Tecnico en Peluqueria y Estetica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Podología', 'nombre_carrera_html' => 'T&eacute;cnico en Podolog&iacute;a','nombre_carrera_no_tilde' => 'Tecnico en Podologia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Prevención de Riesgos', 'nombre_carrera_html' => 'T&eacute;cnico en Prevenci&oacute;n de Riesgos','nombre_carrera_no_tilde' => 'Tecnico en Prevencion de Riesgos'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Procesos Industriales', 'nombre_carrera_html' => 'T&eacute;cnico en Procesos Industriales','nombre_carrera_no_tilde' => 'Tecnico en Procesos Industriales'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Producción de Eventos y Comunicación Social', 'nombre_carrera_html' => 'T&eacute;cnico en Producci&oacute;n de Eventos y Comunicaci&oacute;n Social','nombre_carrera_no_tilde' => 'Tecnico en Produccion de Eventos y Comunicacion Social'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Producción Gráfica y Multimedia', 'nombre_carrera_html' => 'T&eacute;cnico en Producci&oacute;n Gr&aacute;fica y Multimedia','nombre_carrera_no_tilde' => 'Tecnico en Produccion Grafica y Multimedia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Proyectos de Ingeniería', 'nombre_carrera_html' => 'T&eacute;cnico en Proyectos de Ingenier&iacute;a','nombre_carrera_no_tilde' => 'Tecnico en Proyectos de Ingenieria'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Publicidad', 'nombre_carrera_html' => 'T&eacute;cnico en Publicidad','nombre_carrera_no_tilde' => 'Tecnico en Publicidad'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Química (Análisis e Industrial)', 'nombre_carrera_html' => 'T&eacute;cnico en Qu&iacute;mica (An&aacute;lisis e Industrial)','nombre_carrera_no_tilde' => 'Tecnico en Quimica (Analisis e Industrial)'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Radiología y Radioterapia', 'nombre_carrera_html' => 'T&eacute;cnico en Radiolog&iacute;a y Radioterapia','nombre_carrera_no_tilde' => 'Tecnico en Radiologia y Radioterapia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Refrigeración y Climatización', 'nombre_carrera_html' => 'T&eacute;cnico en Refrigeraci&oacute;n y Climatizaci&oacute;n','nombre_carrera_no_tilde' => 'Tecnico en Refrigeracion y Climatizacion'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Relaciones Públicas', 'nombre_carrera_html' => 'T&eacute;cnico en Relaciones P&uacute;blicas','nombre_carrera_no_tilde' => 'Tecnico en Relaciones Publicas'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Servicio Social', 'nombre_carrera_html' => 'T&eacute;cnico en Servicio Social','nombre_carrera_no_tilde' => 'Tecnico en Servicio Social'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Sonido', 'nombre_carrera_html' => 'T&eacute;cnico en Sonido','nombre_carrera_no_tilde' => 'Tecnico en Sonido'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Teatro', 'nombre_carrera_html' => 'T&eacute;cnico en Teatro','nombre_carrera_no_tilde' => 'Tecnico en Teatro'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Telecomunicaciones', 'nombre_carrera_html' => 'T&eacute;cnico en Telecomunicaciones','nombre_carrera_no_tilde' => 'Tecnico en Telecomunicaciones'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Terapias Naturales y Naturopatía', 'nombre_carrera_html' => 'T&eacute;cnico en Terapias Naturales y Naturopat&iacute;a','nombre_carrera_no_tilde' => 'Tecnico en Terapias Naturales y Naturopatia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Topografía', 'nombre_carrera_html' => 'T&eacute;cnico en Topograf&iacute;a','nombre_carrera_no_tilde' => 'Tecnico en Topografia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Traducción e Interpretariado', 'nombre_carrera_html' => 'T&eacute;cnico en Traducci&oacute;n e Interpretariado','nombre_carrera_no_tilde' => 'Tecnico en Traduccion e Interpretariado'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Turismo y Hotelería', 'nombre_carrera_html' => 'T&eacute;cnico en Turismo y Hoteler&iacute;a','nombre_carrera_no_tilde' => 'Tecnico en Turismo y Hoteleria'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico en Vitivinicultura y/o Enología', 'nombre_carrera_html' => 'T&eacute;cnico en Vitivinicultura y/o Enolog&iacute;a','nombre_carrera_no_tilde' => 'Tecnico en Vitivinicultura y/o Enologia'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico Jurídico', 'nombre_carrera_html' => 'T&eacute;cnico Jur&iacute;dico','nombre_carrera_no_tilde' => 'Tecnico Juridico'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico Laboratorista Dental', 'nombre_carrera_html' => 'T&eacute;cnico Laboratorista Dental','nombre_carrera_no_tilde' => 'Tecnico Laboratorista Dental'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Técnico Veterinario', 'nombre_carrera_html' => 'T&eacute;cnico Veterinario','nombre_carrera_no_tilde' => 'Tecnico Veterinario'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Tecnología Médica', 'nombre_carrera_html' => 'Tecnolog&iacute;a M&eacute;dica','nombre_carrera_no_tilde' => 'Tecnologia Medica'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Terapia Ocupacional', 'nombre_carrera_html' => 'Terapia Ocupacional','nombre_carrera_no_tilde' => 'Terapia Ocupacional'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Trabajo Social', 'nombre_carrera_html' => 'Trabajo Social','nombre_carrera_no_tilde' => 'Trabajo Social'));
        \DB::table('carreras')->insertGetId(array('nombre_carrera' => 'Traducción e Interpretación', 'nombre_carrera_html' => 'Traducci&oacute;n e Interpretaci&oacute;n','nombre_carrera_no_tilde' => 'Traduccion e Interpretacion'));
        }

}
