<?php

use Illuminate\Database\Seeder;



/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class DocentesTableSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
        public function run()
        {
        \DB::table('docentes')->insertGetId(array('nombre' => 'Cecilia  ', 'apellido_paterno' => 'Valencia','apellido_materno' => 'Godoy','nombre_html' => 'Cecilia  ','apellido_paterno_html' => 'Valencia','apellido_materno_html' => 'Godoy','nombre_no_tilde' => 'Cecilia  ','apellido_paterno_no_tilde' => 'Valencia','apellido_materno_no_tilde' => 'Godoy','email' => 'cecilia.valencia@inacapmail.cl','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Andrea Lorena ', 'apellido_paterno' => 'Cabrolier','apellido_materno' => 'Balladares','nombre_html' => 'Andrea Lorena ','apellido_paterno_html' => 'Cabrolier','apellido_materno_html' => 'Balladares','nombre_no_tilde' => 'Andrea Lorena ','apellido_paterno_no_tilde' => 'Cabrolier','apellido_materno_no_tilde' => 'Balladares','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Christian Dante ', 'apellido_paterno' => 'Rovano','apellido_materno' => 'Salazar','nombre_html' => 'Christian Dante ','apellido_paterno_html' => 'Rovano','apellido_materno_html' => 'Salazar','nombre_no_tilde' => 'Christian Dante ','apellido_paterno_no_tilde' => 'Rovano','apellido_materno_no_tilde' => 'Salazar','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Rosa Eugenia ', 'apellido_paterno' => 'Seguel','apellido_materno' => 'Correa','nombre_html' => 'Rosa Eugenia ','apellido_paterno_html' => 'Seguel','apellido_materno_html' => 'Correa','nombre_no_tilde' => 'Rosa Eugenia ','apellido_paterno_no_tilde' => 'Seguel','apellido_materno_no_tilde' => 'Correa','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Elena Delfina ', 'apellido_paterno' => 'Barrera','apellido_materno' => 'Gonzalez','nombre_html' => 'Elena Delfina ','apellido_paterno_html' => 'Barrera','apellido_materno_html' => 'Gonzalez','nombre_no_tilde' => 'Elena Delfina ','apellido_paterno_no_tilde' => 'Barrera','apellido_materno_no_tilde' => 'Gonzalez','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Carolina  ', 'apellido_paterno' => 'Ehrmantraut','apellido_materno' => 'Caballero','nombre_html' => 'Carolina  ','apellido_paterno_html' => 'Ehrmantraut','apellido_materno_html' => 'Caballero','nombre_no_tilde' => 'Carolina  ','apellido_paterno_no_tilde' => 'Ehrmantraut','apellido_materno_no_tilde' => 'Caballero','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Patrick Alexander ', 'apellido_paterno' => 'León','apellido_materno' => 'Melita','nombre_html' => 'Patrick Alexander ','apellido_paterno_html' => 'Le&oacute;n','apellido_materno_html' => 'Melita','nombre_no_tilde' => 'Patrick Alexander ','apellido_paterno_no_tilde' => 'Leon','apellido_materno_no_tilde' => 'Melita','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Teresa Jesús ', 'apellido_paterno' => 'Tapia','apellido_materno' => 'Soto','nombre_html' => 'Teresa Jes&uacute;s ','apellido_paterno_html' => 'Tapia','apellido_materno_html' => 'Soto','nombre_no_tilde' => 'Teresa Jesus ','apellido_paterno_no_tilde' => 'Tapia','apellido_materno_no_tilde' => 'Soto','email' => 'teresa.tapia02@inacapmail.cl','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'José Pablo ', 'apellido_paterno' => 'Quezada','apellido_materno' => 'Olguín','nombre_html' => 'Jos&eacute; Pablo ','apellido_paterno_html' => 'Quezada','apellido_materno_html' => 'Olgu&iacute;n','nombre_no_tilde' => 'Jose Pablo ','apellido_paterno_no_tilde' => 'Quezada','apellido_materno_no_tilde' => 'Olguin','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Claudio Arturo ', 'apellido_paterno' => 'Galvez','apellido_materno' => 'Contreras','nombre_html' => 'Claudio Arturo ','apellido_paterno_html' => 'Galvez','apellido_materno_html' => 'Contreras','nombre_no_tilde' => 'Claudio Arturo ','apellido_paterno_no_tilde' => 'Galvez','apellido_materno_no_tilde' => 'Contreras','email' => 'claudio.galvez07@inacapmail.cl','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Jorge Antonio ', 'apellido_paterno' => 'Hormazábal','apellido_materno' => 'Valdós','nombre_html' => 'Jorge Antonio ','apellido_paterno_html' => 'Hormaz&aacute;bal','apellido_materno_html' => 'Vald&oacute;s','nombre_no_tilde' => 'Jorge Antonio ','apellido_paterno_no_tilde' => 'Hormazabal','apellido_materno_no_tilde' => 'Valdes','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Roberto Mauricio Alejandro', 'apellido_paterno' => 'Hernández','apellido_materno' => 'Antinao','nombre_html' => 'Roberto Mauricio Alejandro','apellido_paterno_html' => 'Hern&aacute;ndez','apellido_materno_html' => 'Antinao','nombre_no_tilde' => 'Roberto Mauricio Alejandro','apellido_paterno_no_tilde' => 'Hernandez','apellido_materno_no_tilde' => 'Antinao','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Blanca Araceley ', 'apellido_paterno' => 'Araya','apellido_materno' => 'Diaz','nombre_html' => 'Blanca Araceley ','apellido_paterno_html' => 'Araya','apellido_materno_html' => 'Diaz','nombre_no_tilde' => 'Blanca Araceley ','apellido_paterno_no_tilde' => 'Araya','apellido_materno_no_tilde' => 'Diaz','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Mario Venancio ', 'apellido_paterno' => 'Marchant','apellido_materno' => 'Silva','nombre_html' => 'Mario Venancio ','apellido_paterno_html' => 'Marchant','apellido_materno_html' => 'Silva','nombre_no_tilde' => 'Mario Venancio ','apellido_paterno_no_tilde' => 'Marchant','apellido_materno_no_tilde' => 'Silva','email' => 'mario.marchant@inacapmail.cl','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Pedro Alfonso ', 'apellido_paterno' => 'Fuentealba','apellido_materno' => 'Martinez','nombre_html' => 'Pedro Alfonso ','apellido_paterno_html' => 'Fuentealba','apellido_materno_html' => 'Martinez','nombre_no_tilde' => 'Pedro Alfonso ','apellido_paterno_no_tilde' => 'Fuentealba','apellido_materno_no_tilde' => 'Martinez','email' => 'pedro.fuentealba@inacapmail.cl','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Jose Luis ', 'apellido_paterno' => 'de la Torre','apellido_materno' => 'Urzua','nombre_html' => 'Jose Luis ','apellido_paterno_html' => 'de la Torre','apellido_materno_html' => 'Urzua','nombre_no_tilde' => 'Jose Luis ','apellido_paterno_no_tilde' => 'de la Torre','apellido_materno_no_tilde' => 'Urzua','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Francisco Felipe ', 'apellido_paterno' => 'Cuevas','apellido_materno' => 'Cerón','nombre_html' => 'Francisco Felipe ','apellido_paterno_html' => 'Cuevas','apellido_materno_html' => 'Cer&oacute;n','nombre_no_tilde' => 'Francisco Felipe ','apellido_paterno_no_tilde' => 'Cuevas','apellido_materno_no_tilde' => 'Ceron','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Rodrigo  ', 'apellido_paterno' => 'Toledo','apellido_materno' => 'de los Santos','nombre_html' => 'Rodrigo  ','apellido_paterno_html' => 'Toledo','apellido_materno_html' => 'de los Santos','nombre_no_tilde' => 'Rodrigo  ','apellido_paterno_no_tilde' => 'Toledo','apellido_materno_no_tilde' => 'de los Santos','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Nelson Enrique ', 'apellido_paterno' => 'Vallejos','apellido_materno' => 'Varas','nombre_html' => 'Nelson Enrique ','apellido_paterno_html' => 'Vallejos','apellido_materno_html' => 'Varas','nombre_no_tilde' => 'Nelson Enrique ','apellido_paterno_no_tilde' => 'Vallejos','apellido_materno_no_tilde' => 'Varas','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Susana  ', 'apellido_paterno' => 'Grimalt','apellido_materno' => 'Catalán','nombre_html' => 'Susana  ','apellido_paterno_html' => 'Grimalt','apellido_materno_html' => 'Catal&aacute;n','nombre_no_tilde' => 'Susana  ','apellido_paterno_no_tilde' => 'Grimalt','apellido_materno_no_tilde' => 'Catalan','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Katherine Isabel ', 'apellido_paterno' => 'Navarrete','apellido_materno' => 'Navarro','nombre_html' => 'Katherine Isabel ','apellido_paterno_html' => 'Navarrete','apellido_materno_html' => 'Navarro','nombre_no_tilde' => 'Katherine Isabel ','apellido_paterno_no_tilde' => 'Navarrete','apellido_materno_no_tilde' => 'Navarro','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Francisca  ', 'apellido_paterno' => 'Sanchez','apellido_materno' => 'Mora','nombre_html' => 'Francisca  ','apellido_paterno_html' => 'Sanchez','apellido_materno_html' => 'Mora','nombre_no_tilde' => 'Francisca  ','apellido_paterno_no_tilde' => 'Sanchez','apellido_materno_no_tilde' => 'Mora','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Armin Vladimir ', 'apellido_paterno' => 'Brun','apellido_materno' => 'Ruth','nombre_html' => 'Armin Vladimir ','apellido_paterno_html' => 'Brun','apellido_materno_html' => 'Ruth','nombre_no_tilde' => 'Armin Vladimir ','apellido_paterno_no_tilde' => 'Brun','apellido_materno_no_tilde' => 'Ruth','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Jorge Antonio ', 'apellido_paterno' => 'Rozas','apellido_materno' => 'Cortós','nombre_html' => 'Jorge Antonio ','apellido_paterno_html' => 'Rozas','apellido_materno_html' => 'Cort&oacute;s','nombre_no_tilde' => 'Jorge Antonio ','apellido_paterno_no_tilde' => 'Rozas','apellido_materno_no_tilde' => 'Cortes','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Patricia Monica ', 'apellido_paterno' => 'Cañas','apellido_materno' => 'Lemesch','nombre_html' => 'Patricia Monica ','apellido_paterno_html' => 'Ca&ntilde;as','apellido_materno_html' => 'Lemesch','nombre_no_tilde' => 'Patricia Monica ','apellido_paterno_no_tilde' => 'Cañas','apellido_materno_no_tilde' => 'Lemesch','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Gonzalo Javier ', 'apellido_paterno' => 'Caro','apellido_materno' => 'Celis','nombre_html' => 'Gonzalo Javier ','apellido_paterno_html' => 'Caro','apellido_materno_html' => 'Celis','nombre_no_tilde' => 'Gonzalo Javier ','apellido_paterno_no_tilde' => 'Caro','apellido_materno_no_tilde' => 'Celis','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'José Luis Alberto', 'apellido_paterno' => 'Ramírez','apellido_materno' => 'Ruíz','nombre_html' => 'Jos&eacute; Luis Alberto','apellido_paterno_html' => 'Ram&iacute;rez','apellido_materno_html' => 'Ru&iacute;z','nombre_no_tilde' => 'Jose Luis Alberto','apellido_paterno_no_tilde' => 'Ramirez','apellido_materno_no_tilde' => 'Ruiz','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Luis Wilfredo ', 'apellido_paterno' => 'Flor','apellido_materno' => 'Gonza','nombre_html' => 'Luis Wilfredo ','apellido_paterno_html' => 'Flor','apellido_materno_html' => 'Gonza','nombre_no_tilde' => 'Luis Wilfredo ','apellido_paterno_no_tilde' => 'Flor','apellido_materno_no_tilde' => 'Gonza','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Moisés  ', 'apellido_paterno' => 'Córdova','apellido_materno' => 'Castro','nombre_html' => 'Mois&eacute;s  ','apellido_paterno_html' => 'C&oacute;rdova','apellido_materno_html' => 'Castro','nombre_no_tilde' => 'Moises  ','apellido_paterno_no_tilde' => 'Cordova','apellido_materno_no_tilde' => 'Castro','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Cristian Eduardo ', 'apellido_paterno' => 'González','apellido_materno' => 'Urzúa','nombre_html' => 'Cristian Eduardo ','apellido_paterno_html' => 'Gonz&aacute;lez','apellido_materno_html' => 'Urz&uacute;a','nombre_no_tilde' => 'Cristian Eduardo ','apellido_paterno_no_tilde' => 'Gonzalez','apellido_materno_no_tilde' => 'Urzua','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Francisco Javier ', 'apellido_paterno' => 'González','apellido_materno' => 'Villarroel','nombre_html' => 'Francisco Javier ','apellido_paterno_html' => 'Gonz&aacute;lez','apellido_materno_html' => 'Villarroel','nombre_no_tilde' => 'Francisco Javier ','apellido_paterno_no_tilde' => 'Gonzalez','apellido_materno_no_tilde' => 'Villarroel','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Sergio Andrés ', 'apellido_paterno' => 'Muñoz','apellido_materno' => 'Sasso','nombre_html' => 'Sergio Andr&eacute;s ','apellido_paterno_html' => 'Mu&ntilde;oz','apellido_materno_html' => 'Sasso','nombre_no_tilde' => 'Sergio Andres ','apellido_paterno_no_tilde' => 'Muñoz','apellido_materno_no_tilde' => 'Sasso','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Pedro Ernesto ', 'apellido_paterno' => 'Ulloa','apellido_materno' => 'Morales','nombre_html' => 'Pedro Ernesto ','apellido_paterno_html' => 'Ulloa','apellido_materno_html' => 'Morales','nombre_no_tilde' => 'Pedro Ernesto ','apellido_paterno_no_tilde' => 'Ulloa','apellido_materno_no_tilde' => 'Morales','email' => 'pedro.ulloa04@inacapmail.cl','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Sergio Fernando ', 'apellido_paterno' => 'Figueroa','apellido_materno' => 'Parra','nombre_html' => 'Sergio Fernando ','apellido_paterno_html' => 'Figueroa','apellido_materno_html' => 'Parra','nombre_no_tilde' => 'Sergio Fernando ','apellido_paterno_no_tilde' => 'Figueroa','apellido_materno_no_tilde' => 'Parra','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Francisco Eusebio ', 'apellido_paterno' => 'Vargas','apellido_materno' => 'Barriga','nombre_html' => 'Francisco Eusebio ','apellido_paterno_html' => 'Vargas','apellido_materno_html' => 'Barriga','nombre_no_tilde' => 'Francisco Eusebio ','apellido_paterno_no_tilde' => 'Vargas','apellido_materno_no_tilde' => 'Barriga','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Roger Eliseo ', 'apellido_paterno' => 'Astorga','apellido_materno' => 'Pozo','nombre_html' => 'Roger Eliseo ','apellido_paterno_html' => 'Astorga','apellido_materno_html' => 'Pozo','nombre_no_tilde' => 'Roger Eliseo ','apellido_paterno_no_tilde' => 'Astorga','apellido_materno_no_tilde' => 'Pozo','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Miguel Esteban ', 'apellido_paterno' => 'Aranda','apellido_materno' => 'Macias','nombre_html' => 'Miguel Esteban ','apellido_paterno_html' => 'Aranda','apellido_materno_html' => 'Macias','nombre_no_tilde' => 'Miguel Esteban ','apellido_paterno_no_tilde' => 'Aranda','apellido_materno_no_tilde' => 'Macias','email' => 'miguel.aranda@inacapmail.cl','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Marcell Alejandro ', 'apellido_paterno' => 'Saavedra','apellido_materno' => 'Pinto','nombre_html' => 'Marcell Alejandro ','apellido_paterno_html' => 'Saavedra','apellido_materno_html' => 'Pinto','nombre_no_tilde' => 'Marcell Alejandro ','apellido_paterno_no_tilde' => 'Saavedra','apellido_materno_no_tilde' => 'Pinto','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Lorena Pia ', 'apellido_paterno' => 'Campos','apellido_materno' => 'Valenzuela','nombre_html' => 'Lorena Pia ','apellido_paterno_html' => 'Campos','apellido_materno_html' => 'Valenzuela','nombre_no_tilde' => 'Lorena Pia ','apellido_paterno_no_tilde' => 'Campos','apellido_materno_no_tilde' => 'Valenzuela','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Alejandro Hernán ', 'apellido_paterno' => 'Cuevas ','apellido_materno' => 'Rivero','nombre_html' => 'Alejandro Hern&aacute;n ','apellido_paterno_html' => 'Cuevas ','apellido_materno_html' => 'Rivero','nombre_no_tilde' => 'Alejandro Hernan ','apellido_paterno_no_tilde' => 'Cuevas ','apellido_materno_no_tilde' => 'Rivero','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Christopher Alejandro ', 'apellido_paterno' => 'Contreras','apellido_materno' => 'Escobar','nombre_html' => 'Christopher Alejandro ','apellido_paterno_html' => 'Contreras','apellido_materno_html' => 'Escobar','nombre_no_tilde' => 'Christopher Alejandro ','apellido_paterno_no_tilde' => 'Contreras','apellido_materno_no_tilde' => 'Escobar','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Ruben Andres ', 'apellido_paterno' => 'Coello','apellido_materno' => 'Gonzalez','nombre_html' => 'Ruben Andres ','apellido_paterno_html' => 'Coello','apellido_materno_html' => 'Gonzalez','nombre_no_tilde' => 'Ruben Andres ','apellido_paterno_no_tilde' => 'Coello','apellido_materno_no_tilde' => 'Gonzalez','email' => 'ruben.coello@inacapmail.cl','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'José Alexander ', 'apellido_paterno' => 'Vera','apellido_materno' => 'Puentes','nombre_html' => 'Jos&eacute; Alexander ','apellido_paterno_html' => 'Vera','apellido_materno_html' => 'Puentes','nombre_no_tilde' => 'Jose Alexander ','apellido_paterno_no_tilde' => 'Vera','apellido_materno_no_tilde' => 'Puentes','email' => '','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'Rodrigo Antonio', 'apellido_paterno' => 'Castro','apellido_materno' => 'Avendaño','nombre_html' => 'Rodrigo Antonio','apellido_paterno_html' => 'Castro','apellido_materno_html' => 'Avenda&ntilde;o','nombre_no_tilde' => 'Rodrigo Antonio','apellido_paterno_no_tilde' => 'Castro','apellido_materno_no_tilde' => 'Avendaño','email' => 'rodrigo.castro42@inacapmail.cl','estado' => 1));
        \DB::table('docentes')->insertGetId(array('nombre' => 'José Luis', 'apellido_paterno' => 'Martínez','apellido_materno' => 'Opazo','nombre_html' => 'Jos&eacute; Luis','apellido_paterno_html' => 'Mart&iacute;nez','apellido_materno_html' => 'Opazo','nombre_no_tilde' => 'Jose Luis','apellido_paterno_no_tilde' => 'Martinez','apellido_materno_no_tilde' => 'Opazo','email' => 'jose.martinez05@inacapmail.cl','estado' => 1));

        }

}
