<?php

use Illuminate\Database\Seeder;



/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class InstitucionsTableSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
        public function run()
        {
        \DB::table('tipo_institucions')->insertGetId(array('descripcion' => 'Universidad', 'descripcion_html' => 'Universidad'));
        \DB::table('tipo_institucions')->insertGetId(array('descripcion' => 'Centro de Formación Técnica', 'descripcion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica'));
        \DB::table('tipo_institucions')->insertGetId(array('descripcion' => 'Instituto Profesional', 'descripcion_html' => 'Instituto Profesional'));


        //modulo administración de usuarios
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Pontificia Universidad Católica de Chile', 'nombre_institucion_html' => 'Pontificia Universidad Cat&oacute;lica de Chile','nombre_institucion_no_tilde' => 'Pontificia Universidad Católica de Chile','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Pontificia Universidad Católica de Valparaíso', 'nombre_institucion_html' => 'Pontificia Universidad Cat&oacute;lica de Valpara&iacute;so','nombre_institucion_no_tilde' => 'Pontificia Universidad Católica de Valparaíso','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Academia de Humanismo Cristiano', 'nombre_institucion_html' => 'Universidad Academia de Humanismo Cristiano','nombre_institucion_no_tilde' => 'Universidad Academia de Humanismo Cristiano','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Adolfo Ibáñez', 'nombre_institucion_html' => 'Universidad Adolfo Ib&aacute;&ntilde;ez','nombre_institucion_no_tilde' => 'Universidad Adolfo Ibáñez','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Adventista de Chile', 'nombre_institucion_html' => 'Universidad Adventista de Chile','nombre_institucion_no_tilde' => 'Universidad Adventista de Chile','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Alberto Hurtado', 'nombre_institucion_html' => 'Universidad Alberto Hurtado','nombre_institucion_no_tilde' => 'Universidad Alberto Hurtado','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Andrés Bello ', 'nombre_institucion_html' => 'Universidad Andr&eacute;s Bello ','nombre_institucion_no_tilde' => 'Universidad Andrés Bello ','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Arturo Prat', 'nombre_institucion_html' => 'Universidad Arturo Prat','nombre_institucion_no_tilde' => 'Universidad Arturo Prat','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Austral de Chile', 'nombre_institucion_html' => 'Universidad Austral de Chile','nombre_institucion_no_tilde' => 'Universidad Austral de Chile','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica ALFA', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica ALFA','nombre_institucion_no_tilde' => 'Centro de Formación Técnica ALFA','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Alpes', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Alpes','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Alpes','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Andrés Bello', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Andr&eacute;s Bello','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Andrés Bello','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Barros Arana', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Barros Arana','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Barros Arana','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Cámara de Comercio de Santiago', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica C&aacute;mara de Comercio de Santiago','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Cámara de Comercio de Santiago','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica CEDUC - UCN', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica CEDUC - UCN','nombre_institucion_no_tilde' => 'Centro de Formación Técnica CEDUC - UCN','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica CEITEC', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica CEITEC','nombre_institucion_no_tilde' => 'Centro de Formación Técnica CEITEC','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica CENCO', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica CENCO','nombre_institucion_no_tilde' => 'Centro de Formación Técnica CENCO','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Centro de Enseñanza de Alta Costura Paulina Diard', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Centro de Ense&ntilde;anza de Alta Costura Paulina Diard','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Centro de Enseñanza de Alta Costura Paulina Diard','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Adventista', 'nombre_institucion_html' => 'Instituto Profesional Adventista','nombre_institucion_no_tilde' => 'Instituto Profesional Adventista','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Agrario Adolfo Matthei', 'nombre_institucion_html' => 'Instituto Profesional Agrario Adolfo Matthei','nombre_institucion_no_tilde' => 'Instituto Profesional Agrario Adolfo Matthei','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional AIEP', 'nombre_institucion_html' => 'Instituto Profesional AIEP','nombre_institucion_no_tilde' => 'Instituto Profesional AIEP','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Alemán Wilhelm Von Humboldt', 'nombre_institucion_html' => 'Instituto Profesional Alem&aacute;n Wilhelm Von Humboldt','nombre_institucion_no_tilde' => 'Instituto Profesional Alemán Wilhelm Von Humboldt','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Carlos Casanueva', 'nombre_institucion_html' => 'Instituto Profesional Carlos Casanueva','nombre_institucion_no_tilde' => 'Instituto Profesional Carlos Casanueva','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional CIISA', 'nombre_institucion_html' => 'Instituto Profesional CIISA','nombre_institucion_no_tilde' => 'Instituto Profesional CIISA','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Chileno Británico de Cultura', 'nombre_institucion_html' => 'Instituto Profesional Chileno Brit&aacute;nico de Cultura','nombre_institucion_no_tilde' => 'Instituto Profesional Chileno Británico de Cultura','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Chileno Norteamericano', 'nombre_institucion_html' => 'Instituto Profesional Chileno Norteamericano','nombre_institucion_no_tilde' => 'Instituto Profesional Chileno Norteamericano','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional de Arte y Comunicación ARCOS', 'nombre_institucion_html' => 'Instituto Profesional de Arte y Comunicaci&oacute;n ARCOS','nombre_institucion_no_tilde' => 'Instituto Profesional de Arte y Comunicación ARCOS','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Autónoma de Chile', 'nombre_institucion_html' => 'Universidad Aut&oacute;noma de Chile','nombre_institucion_no_tilde' => 'Universidad Autónoma de Chile','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Bernardo OHiggins', 'nombre_institucion_html' => 'Universidad Bernardo OHiggins','nombre_institucion_no_tilde' => 'Universidad Bernardo OHiggins','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Bolivariana', 'nombre_institucion_html' => 'Universidad Bolivariana','nombre_institucion_no_tilde' => 'Universidad Bolivariana','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Católica Cardenal Raúl Silva Henríquez', 'nombre_institucion_html' => 'Universidad Cat&oacute;lica Cardenal Ra&uacute;l Silva Henr&iacute;quez','nombre_institucion_no_tilde' => 'Universidad Católica Cardenal Raúl Silva Henríquez','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Católica de la Santísima Concepción', 'nombre_institucion_html' => 'Universidad Cat&oacute;lica de la Sant&iacute;sima Concepci&oacute;n','nombre_institucion_no_tilde' => 'Universidad Católica de la Santísima Concepción','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Católica de Temuco', 'nombre_institucion_html' => 'Universidad Cat&oacute;lica de Temuco','nombre_institucion_no_tilde' => 'Universidad Católica de Temuco','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Católica del Maule', 'nombre_institucion_html' => 'Universidad Cat&oacute;lica del Maule','nombre_institucion_no_tilde' => 'Universidad Católica del Maule','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Católica del Norte', 'nombre_institucion_html' => 'Universidad Cat&oacute;lica del Norte','nombre_institucion_no_tilde' => 'Universidad Católica del Norte','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Central de Chile', 'nombre_institucion_html' => 'Universidad Central de Chile','nombre_institucion_no_tilde' => 'Universidad Central de Chile','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Chileno Británica de Cultura', 'nombre_institucion_html' => 'Universidad Chileno Brit&aacute;nica de Cultura','nombre_institucion_no_tilde' => 'Universidad Chileno Británica de Cultura','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Aconcagua', 'nombre_institucion_html' => 'Universidad de Aconcagua','nombre_institucion_no_tilde' => 'Universidad de Aconcagua','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Antofagasta', 'nombre_institucion_html' => 'Universidad de Antofagasta','nombre_institucion_no_tilde' => 'Universidad de Antofagasta','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Arte y Ciencias Sociales ARCIS', 'nombre_institucion_html' => 'Universidad de Arte y Ciencias Sociales ARCIS','nombre_institucion_no_tilde' => 'Universidad de Arte y Ciencias Sociales ARCIS','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Artes, Ciencias y Comunicación - UNIACC', 'nombre_institucion_html' => 'Universidad de Artes, Ciencias y Comunicaci&oacute;n - UNIACC','nombre_institucion_no_tilde' => 'Universidad de Artes, Ciencias y Comunicación - UNIACC','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Atacama', 'nombre_institucion_html' => 'Universidad de Atacama','nombre_institucion_no_tilde' => 'Universidad de Atacama','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Concepción', 'nombre_institucion_html' => 'Universidad de Concepci&oacute;n','nombre_institucion_no_tilde' => 'Universidad de Concepción','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Chile', 'nombre_institucion_html' => 'Universidad de Chile','nombre_institucion_no_tilde' => 'Universidad de Chile','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de La Frontera', 'nombre_institucion_html' => 'Universidad de La Frontera','nombre_institucion_no_tilde' => 'Universidad de La Frontera','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de La Serena', 'nombre_institucion_html' => 'Universidad de La Serena','nombre_institucion_no_tilde' => 'Universidad de La Serena','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Las Américas', 'nombre_institucion_html' => 'Universidad de Las Am&eacute;ricas','nombre_institucion_no_tilde' => 'Universidad de Las Américas','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Los Andes', 'nombre_institucion_html' => 'Universidad de Los Andes','nombre_institucion_no_tilde' => 'Universidad de Los Andes','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Los Lagos', 'nombre_institucion_html' => 'Universidad de Los Lagos','nombre_institucion_no_tilde' => 'Universidad de Los Lagos','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Magallanes', 'nombre_institucion_html' => 'Universidad de Magallanes','nombre_institucion_no_tilde' => 'Universidad de Magallanes','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Playa Ancha de Ciencias de la Educación', 'nombre_institucion_html' => 'Universidad de Playa Ancha de Ciencias de la Educaci&oacute;n','nombre_institucion_no_tilde' => 'Universidad de Playa Ancha de Ciencias de la Educación','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Santiago de Chile', 'nombre_institucion_html' => 'Universidad de Santiago de Chile','nombre_institucion_no_tilde' => 'Universidad de Santiago de Chile','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Talca', 'nombre_institucion_html' => 'Universidad de Talca','nombre_institucion_no_tilde' => 'Universidad de Talca','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Tarapacá', 'nombre_institucion_html' => 'Universidad de Tarapac&aacute;','nombre_institucion_no_tilde' => 'Universidad de Tarapacá','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Valparaíso', 'nombre_institucion_html' => 'Universidad de Valpara&iacute;so','nombre_institucion_no_tilde' => 'Universidad de Valparaíso','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad de Viña del Mar', 'nombre_institucion_html' => 'Universidad de Vi&ntilde;a del Mar','nombre_institucion_no_tilde' => 'Universidad de Viña del Mar','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad del Bío-Bío', 'nombre_institucion_html' => 'Universidad del B&iacute;o-B&iacute;o','nombre_institucion_no_tilde' => 'Universidad del Bío-Bío','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad del Desarrollo', 'nombre_institucion_html' => 'Universidad del Desarrollo','nombre_institucion_no_tilde' => 'Universidad del Desarrollo','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad del Mar', 'nombre_institucion_html' => 'Universidad del Mar','nombre_institucion_no_tilde' => 'Universidad del Mar','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad del Pacífico', 'nombre_institucion_html' => 'Universidad del Pac&iacute;fico','nombre_institucion_no_tilde' => 'Universidad del Pacífico','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Diego Portales', 'nombre_institucion_html' => 'Universidad Diego Portales','nombre_institucion_no_tilde' => 'Universidad Diego Portales','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Finis Terrae', 'nombre_institucion_html' => 'Universidad Finis Terrae','nombre_institucion_no_tilde' => 'Universidad Finis Terrae','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Gabriela Mistral', 'nombre_institucion_html' => 'Universidad Gabriela Mistral','nombre_institucion_no_tilde' => 'Universidad Gabriela Mistral','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Iberoamericana de Ciencias y Tecnología, UNICIT', 'nombre_institucion_html' => 'Universidad Iberoamericana de Ciencias y Tecnolog&iacute;a, UNICIT','nombre_institucion_no_tilde' => 'Universidad Iberoamericana de Ciencias y Tecnología, UNICIT','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad La Araucana', 'nombre_institucion_html' => 'Universidad La Araucana','nombre_institucion_no_tilde' => 'Universidad La Araucana','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad La República', 'nombre_institucion_html' => 'Universidad La Rep&uacute;blica','nombre_institucion_no_tilde' => 'Universidad La República','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Los Leones', 'nombre_institucion_html' => 'Universidad Los Leones','nombre_institucion_no_tilde' => 'Universidad Los Leones','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Mayor', 'nombre_institucion_html' => 'Universidad Mayor','nombre_institucion_no_tilde' => 'Universidad Mayor','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Metropolitana de Ciencias de la Educación', 'nombre_institucion_html' => 'Universidad Metropolitana de Ciencias de la Educaci&oacute;n','nombre_institucion_no_tilde' => 'Universidad Metropolitana de Ciencias de la Educación','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Miguel de Cervantes', 'nombre_institucion_html' => 'Universidad Miguel de Cervantes','nombre_institucion_no_tilde' => 'Universidad Miguel de Cervantes','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Pedro de Valdivia', 'nombre_institucion_html' => 'Universidad Pedro de Valdivia','nombre_institucion_no_tilde' => 'Universidad Pedro de Valdivia','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad San Sebastián', 'nombre_institucion_html' => 'Universidad San Sebasti&aacute;n','nombre_institucion_no_tilde' => 'Universidad San Sebastián','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Santo Tomás', 'nombre_institucion_html' => 'Universidad Santo Tom&aacute;s','nombre_institucion_no_tilde' => 'Universidad Santo Tomás','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad SEK', 'nombre_institucion_html' => 'Universidad SEK','nombre_institucion_no_tilde' => 'Universidad SEK','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Técnica Federico Santa María', 'nombre_institucion_html' => 'Universidad T&eacute;cnica Federico Santa Mar&iacute;a','nombre_institucion_no_tilde' => 'Universidad Técnica Federico Santa María','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Tecnológica de Chile INACAP', 'nombre_institucion_html' => 'Universidad Tecnol&oacute;gica de Chile INACAP','nombre_institucion_no_tilde' => 'Universidad Tecnológica de Chile INACAP','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad Tecnológica Metropolitana', 'nombre_institucion_html' => 'Universidad Tecnol&oacute;gica Metropolitana','nombre_institucion_no_tilde' => 'Universidad Tecnológica Metropolitana','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Universidad UCINF', 'nombre_institucion_html' => 'Universidad UCINF','nombre_institucion_no_tilde' => 'Universidad UCINF','id_tipo_institucion' => 1));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Centro Tecnológico Superior INFOMED', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Centro Tecnol&oacute;gico Superior INFOMED','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Centro Tecnológico Superior INFOMED','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica CEPA de la III Región', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica CEPA de la III Regi&oacute;n','nombre_institucion_no_tilde' => 'Centro de Formación Técnica CEPA de la III Región','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica CEPONAL', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica CEPONAL','nombre_institucion_no_tilde' => 'Centro de Formación Técnica CEPONAL','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica CRECIC', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica CRECIC','nombre_institucion_no_tilde' => 'Centro de Formación Técnica CRECIC','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica CROWNLIET', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica CROWNLIET','nombre_institucion_no_tilde' => 'Centro de Formación Técnica CROWNLIET','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica de ENAC', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica de ENAC','nombre_institucion_no_tilde' => 'Centro de Formación Técnica de ENAC','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica de la Industria Gráfica', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica de la Industria Gr&aacute;fica','nombre_institucion_no_tilde' => 'Centro de Formación Técnica de la Industria Gráfica','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica de Tarapacá', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica de Tarapac&aacute;','nombre_institucion_no_tilde' => 'Centro de Formación Técnica de Tarapacá','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica del Medio Ambiente', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica del Medio Ambiente','nombre_institucion_no_tilde' => 'Centro de Formación Técnica del Medio Ambiente','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica DUOC UC', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica DUOC UC','nombre_institucion_no_tilde' => 'Centro de Formación Técnica DUOC UC','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica EDUCAP', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica EDUCAP','nombre_institucion_no_tilde' => 'Centro de Formación Técnica EDUCAP','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Escuela Culinaria Francesa ECOLE', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Escuela Culinaria Francesa ECOLE','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Escuela Culinaria Francesa ECOLE','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Escuela de Artes Aplicadas Oficios del Fuego', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Escuela de Artes Aplicadas Oficios del Fuego','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Escuela de Artes Aplicadas Oficios del Fuego','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Escuela de Interpretes INCENI', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Escuela de Interpretes INCENI','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Escuela de Interpretes INCENI','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Escuela Superior de Administración de Negocios del Norte - ESANE DEL NORTE', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Escuela Superior de Administraci&oacute;n de Negocios del Norte - ESANE DEL NORTE','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Escuela Superior de Administración de Negocios del Norte - ESANE DEL NORTE','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Estudio Profesor Valero', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Estudio Profesor Valero','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Estudio Profesor Valero','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica FINNING', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica FINNING','nombre_institucion_no_tilde' => 'Centro de Formación Técnica FINNING','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica FONTANAR', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica FONTANAR','nombre_institucion_no_tilde' => 'Centro de Formación Técnica FONTANAR','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica ICEL', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica ICEL','nombre_institucion_no_tilde' => 'Centro de Formación Técnica ICEL','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica INACAP', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica INACAP','nombre_institucion_no_tilde' => 'Centro de Formación Técnica INACAP','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Instituto Central de Capacitación Educacional ICCE', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Instituto Central de Capacitaci&oacute;n Educacional ICCE','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Instituto Central de Capacitación Educacional ICCE','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Instituto de Secretariado INSEC', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Instituto de Secretariado INSEC','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Instituto de Secretariado INSEC','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Instituto Superior Alemán de Comercio INSALCO', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Instituto Superior Alem&aacute;n de Comercio INSALCO','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Instituto Superior Alemán de Comercio INSALCO','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Instituto Superior de Estudios Jurídicos CANON', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Instituto Superior de Estudios Jur&iacute;dicos CANON','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Instituto Superior de Estudios Jurídicos CANON','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Instituto Técnológico de Chile - I.T.C.', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Instituto T&eacute;cnol&oacute;gico de Chile - I.T.C.','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Instituto Técnológico de Chile - I.T.C.','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica IPROSEC', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica IPROSEC','nombre_institucion_no_tilde' => 'Centro de Formación Técnica IPROSEC','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Juan Bohon', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Juan Bohon','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Juan Bohon','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica La Araucana', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica La Araucana','nombre_institucion_no_tilde' => 'Centro de Formación Técnica La Araucana','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica LAPLACE', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica LAPLACE','nombre_institucion_no_tilde' => 'Centro de Formación Técnica LAPLACE','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Los Lagos', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Los Lagos','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Los Lagos','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Los Leones', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Los Leones','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Los Leones','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Lota-Arauco', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Lota-Arauco','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Lota-Arauco','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Luis Alberto Vera', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Luis Alberto Vera','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Luis Alberto Vera','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica MAGNOS', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica MAGNOS','nombre_institucion_no_tilde' => 'Centro de Formación Técnica MAGNOS','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica MANPOWER', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica MANPOWER','nombre_institucion_no_tilde' => 'Centro de Formación Técnica MANPOWER','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Massachusetts', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Massachusetts','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Massachusetts','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica PROANDES', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica PROANDES','nombre_institucion_no_tilde' => 'Centro de Formación Técnica PROANDES','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica PRODATA', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica PRODATA','nombre_institucion_no_tilde' => 'Centro de Formación Técnica PRODATA','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica PROFASOC', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica PROFASOC','nombre_institucion_no_tilde' => 'Centro de Formación Técnica PROFASOC','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica PROTEC', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica PROTEC','nombre_institucion_no_tilde' => 'Centro de Formación Técnica PROTEC','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica San Agustín de Talca', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica San Agust&iacute;n de Talca','nombre_institucion_no_tilde' => 'Centro de Formación Técnica San Agustín de Talca','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Santo Tomás', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Santo Tom&aacute;s','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Santo Tomás','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Simón Bolivar', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Sim&oacute;n Bolivar','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Simón Bolivar','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica Teodoro Wickel Kluwen', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica Teodoro Wickel Kluwen','nombre_institucion_no_tilde' => 'Centro de Formación Técnica Teodoro Wickel Kluwen','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica U. VALPO', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica U. VALPO','nombre_institucion_no_tilde' => 'Centro de Formación Técnica U. VALPO','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica UCEVALPO', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica UCEVALPO','nombre_institucion_no_tilde' => 'Centro de Formación Técnica UCEVALPO','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Centro de Formación Técnica UDA', 'nombre_institucion_html' => 'Centro de Formaci&oacute;n T&eacute;cnica UDA','nombre_institucion_no_tilde' => 'Centro de Formación Técnica UDA','id_tipo_institucion' => 2));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional de Artes Escénicas Karen Konnolly', 'nombre_institucion_html' => 'Instituto Profesional de Artes Esc&eacute;nicas Karen Konnolly','nombre_institucion_no_tilde' => 'Instituto Profesional de Artes Escénicas Karen Konnolly','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional de Ciencias de la Computación Acuario Data', 'nombre_institucion_html' => 'Instituto Profesional de Ciencias de la Computaci&oacute;n Acuario Data','nombre_institucion_no_tilde' => 'Instituto Profesional de Ciencias de la Computación Acuario Data','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional de Ciencias y Artes INCACEA', 'nombre_institucion_html' => 'Instituto Profesional de Ciencias y Artes INCACEA','nombre_institucion_no_tilde' => 'Instituto Profesional de Ciencias y Artes INCACEA','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional de Ciencias y Educación Helen Keller', 'nombre_institucion_html' => 'Instituto Profesional de Ciencias y Educaci&oacute;n Helen Keller','nombre_institucion_no_tilde' => 'Instituto Profesional de Ciencias y Educación Helen Keller','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional de Chile', 'nombre_institucion_html' => 'Instituto Profesional de Chile','nombre_institucion_no_tilde' => 'Instituto Profesional de Chile','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional de ENAC', 'nombre_institucion_html' => 'Instituto Profesional de ENAC','nombre_institucion_no_tilde' => 'Instituto Profesional de ENAC','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional de Los ángeles', 'nombre_institucion_html' => 'Instituto Profesional de Los &Aacute;ngeles','nombre_institucion_no_tilde' => 'Instituto Profesional de Los ángeles','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional del Comercio', 'nombre_institucion_html' => 'Instituto Profesional del Comercio','nombre_institucion_no_tilde' => 'Instituto Profesional del Comercio','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional del Valle Central', 'nombre_institucion_html' => 'Instituto Profesional del Valle Central','nombre_institucion_no_tilde' => 'Instituto Profesional del Valle Central','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Diego Portales', 'nombre_institucion_html' => 'Instituto Profesional Diego Portales','nombre_institucion_no_tilde' => 'Instituto Profesional Diego Portales','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Dr. Virginio Gómez G.', 'nombre_institucion_html' => 'Instituto Profesional Dr. Virginio G&oacute;mez G.','nombre_institucion_no_tilde' => 'Instituto Profesional Dr. Virginio Gómez G.','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional DUOC UC', 'nombre_institucion_html' => 'Instituto Profesional DUOC UC','nombre_institucion_no_tilde' => 'Instituto Profesional DUOC UC','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional EATRI Instituto Profesional', 'nombre_institucion_html' => 'Instituto Profesional EATRI Instituto Profesional','nombre_institucion_no_tilde' => 'Instituto Profesional EATRI Instituto Profesional','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Escuela de Cine de Chile', 'nombre_institucion_html' => 'Instituto Profesional Escuela de Cine de Chile','nombre_institucion_no_tilde' => 'Instituto Profesional Escuela de Cine de Chile','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Escuela de Contadores Auditores de Santiago', 'nombre_institucion_html' => 'Instituto Profesional Escuela de Contadores Auditores de Santiago','nombre_institucion_no_tilde' => 'Instituto Profesional Escuela de Contadores Auditores de Santiago','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Escuela Moderna de Música', 'nombre_institucion_html' => 'Instituto Profesional Escuela Moderna de M&uacute;sica','nombre_institucion_no_tilde' => 'Instituto Profesional Escuela Moderna de Música','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional ESUCOMEX', 'nombre_institucion_html' => 'Instituto Profesional ESUCOMEX','nombre_institucion_no_tilde' => 'Instituto Profesional ESUCOMEX','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Hogar Catequístico', 'nombre_institucion_html' => 'Instituto Profesional Hogar Catequ&iacute;stico','nombre_institucion_no_tilde' => 'Instituto Profesional Hogar Catequístico','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional INACAP', 'nombre_institucion_html' => 'Instituto Profesional INACAP','nombre_institucion_no_tilde' => 'Instituto Profesional INACAP','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Instituto de Estudios Bancarios Guillermo Subercaseaux', 'nombre_institucion_html' => 'Instituto Profesional Instituto de Estudios Bancarios Guillermo Subercaseaux','nombre_institucion_no_tilde' => 'Instituto Profesional Instituto de Estudios Bancarios Guillermo Subercaseaux','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Instituto Internacional de Artes Culinarias y Servicios', 'nombre_institucion_html' => 'Instituto Profesional Instituto Internacional de Artes Culinarias y Servicios','nombre_institucion_no_tilde' => 'Instituto Profesional Instituto Internacional de Artes Culinarias y Servicios','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Instituto Nacional del Fútbol', 'nombre_institucion_html' => 'Instituto Profesional Instituto Nacional del F&uacute;tbol','nombre_institucion_no_tilde' => 'Instituto Profesional Instituto Nacional del Fútbol','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Instituto Superior de Artes y Ciencias de la Comunicación', 'nombre_institucion_html' => 'Instituto Profesional Instituto Superior de Artes y Ciencias de la Comunicaci&oacute;n','nombre_institucion_no_tilde' => 'Instituto Profesional Instituto Superior de Artes y Ciencias de la Comunicación','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional IPG', 'nombre_institucion_html' => 'Instituto Profesional IPG','nombre_institucion_no_tilde' => 'Instituto Profesional IPG','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional La Araucana', 'nombre_institucion_html' => 'Instituto Profesional La Araucana','nombre_institucion_no_tilde' => 'Instituto Profesional La Araucana','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Latinoamericano de Comercio Exterior', 'nombre_institucion_html' => 'Instituto Profesional Latinoamericano de Comercio Exterior','nombre_institucion_no_tilde' => 'Instituto Profesional Latinoamericano de Comercio Exterior','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Libertador de Los Andes', 'nombre_institucion_html' => 'Instituto Profesional Libertador de Los Andes','nombre_institucion_no_tilde' => 'Instituto Profesional Libertador de Los Andes','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Los Lagos', 'nombre_institucion_html' => 'Instituto Profesional Los Lagos','nombre_institucion_no_tilde' => 'Instituto Profesional Los Lagos','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Los Leones', 'nombre_institucion_html' => 'Instituto Profesional Los Leones','nombre_institucion_no_tilde' => 'Instituto Profesional Los Leones','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Mar Futuro', 'nombre_institucion_html' => 'Instituto Profesional Mar Futuro','nombre_institucion_no_tilde' => 'Instituto Profesional Mar Futuro','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Projazz', 'nombre_institucion_html' => 'Instituto Profesional Projazz','nombre_institucion_no_tilde' => 'Instituto Profesional Projazz','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Providencia', 'nombre_institucion_html' => 'Instituto Profesional Providencia','nombre_institucion_no_tilde' => 'Instituto Profesional Providencia','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Santo Tomás', 'nombre_institucion_html' => 'Instituto Profesional Santo Tom&aacute;s','nombre_institucion_no_tilde' => 'Instituto Profesional Santo Tomás','id_tipo_institucion' => 3));
        \DB::table('institucions')->insertGetId(array('nombre_institucion' => 'Instituto Profesional Vertical', 'nombre_institucion_html' => 'Instituto Profesional Vertical','nombre_institucion_no_tilde' => 'Instituto Profesional Vertical','id_tipo_institucion' => 3));

        }

}
